/**
 * Areas of ownership for engineering teams.
 * Used for squad assignment and triage.
 */

export interface AreaOfOwnership {
  name: string;
  squad: string;
  owners: string[];
  category: 'open-source' | 'cloud';
  keywords: string[];
  assignWhen: string;
}

export const categories: AreaOfOwnership[] = [
  // Open Source Areas
  {
    name: 'Playground',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['Playground', 'Dev Playground', 'UI', 'User Interface'],
    assignWhen: 'Issue mentions the playground UI or development playground',
  },
  {
    name: 'Streaming',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Streaming', 'Stream', 'SSE', 'Server-Sent Events', 'Real-time', 'Workflow Streaming'],
    assignWhen: 'Issue mentions streaming responses, SSE, or real-time data streaming',
  },
  {
    name: 'CI / Tests',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['CI', 'Tests', 'Testing', 'GitHub Actions', 'Jest', 'Vitest', 'Test Utils'],
    assignWhen: 'Issue mentions CI, testing infrastructure, or test utilities',
  },
  {
    name: 'Bundler',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['Bundler', 'Bundlerooski', 'Build', 'Webpack', 'Esbuild', 'Module'],
    assignWhen: 'Issue mentions bundling, build process, or module bundling',
  },
  {
    name: 'Deployer',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['Deployer', 'Deploy', 'Deployment', 'Cloudflare', 'Cloudflare Workers'],
    assignWhen: 'Issue mentions deployment tools or deploy commands',
  },
  {
    name: 'CLI',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['CLI', 'Command Line', 'Terminal', 'mastra init', 'mastra dev'],
    assignWhen: 'Issue mentions the Mastra CLI or terminal commands',
  },
  {
    name: 'Client SDK - JS',
    squad: 'trio-wp',
    owners: ['trio-wp'],
    category: 'open-source',
    keywords: ['Client SDK', 'SDK', 'ai-sdk', 'assistant-ui', 'React', 'Frontend', 'UI Components'],
    assignWhen: 'Issue mentions JavaScript/TypeScript client SDK, frontend integration, or React hooks',
  },
  {
    name: 'Agents',
    squad: 'trio-tb',
    owners: ['trio-tb'],
    category: 'open-source',
    keywords: ['Agent', 'Agents', 'AI Agent', 'LLM', 'OpenAI', 'Claude', 'Anthropic', 'Gemini', 'Bedrock', 'OpenRouter'],
    assignWhen: 'Issue mentions agent functionality or AI model integration',
  },
  {
    name: 'Tools',
    squad: 'trio-tb',
    owners: ['trio-tb'],
    category: 'open-source',
    keywords: ['Tools', 'Tool', 'Function Calling', 'Tool Execution'],
    assignWhen: 'Issue mentions agent tools, tool definitions, or function calling',
  },
  {
    name: 'Memory',
    squad: 'trio-tb',
    owners: ['trio-tb'],
    category: 'open-source',
    keywords: ['Memory', 'Conversation Memory', 'Chat History', 'Context Retention'],
    assignWhen: 'Issue mentions memory functionality or conversation history',
  },
  {
    name: 'MCP',
    squad: 'trio-tb',
    owners: ['trio-tb'],
    category: 'open-source',
    keywords: ['MCP', 'Model Context Protocol', 'MCP Server', 'MCP Client'],
    assignWhen: 'Issue mentions MCP or Model Context Protocol',
  },
  {
    name: 'Processors',
    squad: 'trio-tb',
    owners: ['trio-tb'],
    category: 'open-source',
    keywords: ['Processors', 'Guardrails', 'Input Output', 'I/O', 'Validation', 'Transform'],
    assignWhen: 'Issue mentions input/output processors, guardrails, or data transformation',
  },
  {
    name: 'Workflows',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Workflow', 'Workflows', 'Steps', 'Suspend', 'Resume', 'Orchestration'],
    assignWhen: 'Issue mentions workflow engine, steps, or workflow execution',
  },
  {
    name: 'Networks',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Network', 'Networks', 'Agent Network', 'Multi-agent', 'Agent Communication'],
    assignWhen: 'Issue mentions agent networks or multi-agent systems',
  },
  {
    name: 'Storage',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Storage', 'Database', 'Databases', 'Persistence', 'LibSQL', 'PostgreSQL', 'Vector DB'],
    assignWhen: 'Issue mentions data storage, databases, or persistence',
  },
  {
    name: 'RAG',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['RAG', 'Retrieval', 'Augmented Generation', 'Vector Search', 'Embeddings'],
    assignWhen: 'Issue mentions RAG, retrieval, or vector search',
  },
  {
    name: 'Server Cache',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Cache', 'Server Cache', 'Caching', 'Performance'],
    assignWhen: 'Issue mentions server-side caching or cache management',
  },
  {
    name: 'Pubsub',
    squad: 'trio-tnt',
    owners: ['trio-tnt'],
    category: 'open-source',
    keywords: ['Pubsub', 'Publish', 'Subscribe', 'Events', 'Message Queue'],
    assignWhen: 'Issue mentions publish/subscribe or event systems',
  },
  {
    name: 'Voice',
    squad: 'trio-tron',
    owners: ['trio-tron'],
    category: 'open-source',
    keywords: ['Voice', 'Speech', 'Audio', 'TTS', 'STT', 'Text to Speech', 'Speech to Text'],
    assignWhen: 'Issue mentions voice AI, speech processing, or audio',
  },
  {
    name: 'Evals',
    squad: 'trio-tracery',
    owners: ['trio-tracery'],
    category: 'open-source',
    keywords: ['Evals', 'Evaluation', 'Evaluations', 'Benchmarks', 'Quality Metrics'],
    assignWhen: 'Issue mentions evaluations, testing AI outputs, or benchmarking',
  },
  {
    name: 'Observability',
    squad: 'trio-tracery',
    owners: ['trio-tracery'],
    category: 'open-source',
    keywords: ['Observability', 'Telemetry', 'Logging', 'Tracing', 'Monitoring', 'Metrics'],
    assignWhen: 'Issue mentions logging, telemetry, tracing, or monitoring',
  },
  {
    name: 'Examples',
    squad: 'Growth',
    owners: ['Growth'],
    category: 'open-source',
    keywords: ['Examples', 'Example', 'Sample', 'Tutorial', 'Starter', 'Template'],
    assignWhen: 'Issue mentions example projects, sample code, or tutorials',
  },
  {
    name: 'Docs (content)',
    squad: 'Growth',
    owners: ['Growth'],
    category: 'open-source',
    keywords: ['Docs', 'Documentation', 'Guide', 'API Docs', 'README'],
    assignWhen: 'Issue mentions documentation content, guides, or API documentation',
  },
  {
    name: 'Docs (dev)',
    squad: 'Growth',
    owners: ['Growth'],
    category: 'open-source',
    keywords: ['Docs Dev', 'MDX', 'Docs Site', 'Docs Tooling'],
    assignWhen: 'Issue mentions documentation infrastructure or docs site development',
  },
  {
    name: 'Website',
    squad: 'Growth',
    owners: ['Growth'],
    category: 'open-source',
    keywords: ['Website', 'Landing Page', 'Marketing', 'mastra.ai'],
    assignWhen: 'Issue mentions the marketing website or landing pages',
  },
  {
    name: 'Prod analytics',
    squad: 'Growth',
    owners: ['Growth'],
    category: 'open-source',
    keywords: ['Analytics', 'Prod Analytics', 'Usage Tracking', 'Metrics Dashboard'],
    assignWhen: 'Issue mentions production analytics or usage tracking',
  },

  // Cloud Areas
  {
    name: 'Cloud Admin',
    squad: 'trio-tron',
    owners: ['trio-tron', 'trio-tracery'],
    category: 'cloud',
    keywords: ['Admin', 'Dashboard', 'User Management', 'Project Management', 'Mastra Cloud'],
    assignWhen: 'Issue mentions Mastra Cloud admin dashboard or user/project management',
  },
  {
    name: 'Cloud Runner',
    squad: 'trio-tron',
    owners: ['trio-tron', 'trio-tracery'],
    category: 'cloud',
    keywords: ['Runner', 'Cloud Runner', 'Execution', 'Cloud Execution'],
    assignWhen: 'Issue mentions cloud runner or workflow/agent execution in cloud',
  },
  {
    name: 'Cloud Builder',
    squad: 'trio-tron',
    owners: ['trio-tron', 'trio-tracery'],
    category: 'cloud',
    keywords: ['Builder', 'Cloud Builder', 'Build Pipeline', 'Cloud Build'],
    assignWhen: 'Issue mentions cloud builder or deployment pipeline',
  },
  {
    name: 'Cloud Platform API',
    squad: 'trio-tron',
    owners: ['trio-tron', 'trio-tracery'],
    category: 'cloud',
    keywords: ['Platform API', 'Internal API', 'Cloud API'],
    assignWhen: 'Issue mentions platform API or internal cloud APIs',
  },
  {
    name: 'Cloud Business API',
    squad: 'trio-tron',
    owners: ['trio-tron', 'trio-tracery'],
    category: 'cloud',
    keywords: ['Business API', 'Billing API', 'Customer API'],
    assignWhen: 'Issue mentions business API, billing, or customer-facing APIs',
  },
  {
    name: 'Cloud Infrastructure',
    squad: 'trio-tron',
    owners: ['trio-tron'],
    category: 'cloud',
    keywords: ['Infrastructure', 'AWS', 'Kubernetes', 'DevOps', 'Scaling', 'Cloud Infra'],
    assignWhen: 'Issue mentions cloud infrastructure, AWS, Kubernetes, or DevOps',
  },
];

// Login to Discord with your bot token
export const BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;
